platform :ios, '15.0'
use_frameworks!

target 'UniversalTranslator' do
  # Firebase pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  
  # Additional useful pods
  pod 'FirebaseFirestoreSwift'
  
  target 'UniversalTranslatorTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end