name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          report_format: sarif
          report_path: gitleaks.sarif
          redact: true
        env:
          GITLEAKS_CONFIG: .gitleaks.toml

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('gitleaks.sarif') != ''
        with:
          sarif_file: gitleaks.sarif

